// AI Market Intelligence card — backed by POST /ai/commentary (Groq, cached server-side).
// Degrades gracefully on 502 so it never blocks the rest of the dashboard.
import type { Pair } from '../types/api'
import { useCommentary } from '../hooks/useCommentary'
import { Skeleton } from './ui'
import { ApiError } from '../api/client'

export function MarketIntelligence({ pair, date }: { pair: Pair; date: string | undefined }) {
  const commentary = useCommentary(pair, date)

  let text
  if (!date || commentary.isLoading) text = <Skeleton height={64} />
  else if (commentary.isError) {
    const msg =
      commentary.error instanceof ApiError && commentary.error.isAiDown
        ? 'AI commentary is temporarily unavailable.'
        : 'Could not load commentary.'
    text = (
      <p className="ai-text" style={{ color: 'var(--text-mute)' }}>
        {msg}
      </p>
    )
  } else text = <p className="ai-text">{commentary.data?.commentary}</p>

  const stamp = commentary.data?.date
    ? new Date(commentary.data.date + 'T00:00:00').toLocaleDateString('en-GB', {
        year: 'numeric',
        month: 'short',
        day: '2-digit',
      })
    : '—'

  return (
    <section className="card ai-card">
      <div className="ai-spark" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
          <path d="M12 3 13.6 9.4 20 11 13.6 12.6 12 19 10.4 12.6 4 11 10.4 9.4 12 3z" />
          <path d="M19 3l.6 2.4L22 6l-2.4.6L19 9l-.6-2.4L16 6l2.4-.6L19 3z" />
        </svg>
      </div>
      <div className="ai-body">
        <div className="ai-title-row">
          <h3>Market Intelligence</h3>
          <span className="ai-tag">AI · Beta</span>
        </div>
        {text}
        <div className="ai-foot">
          Generated by Colombus Capital AI Engine · model.fx-r1 · <span className="mono">{stamp}</span>
        </div>
      </div>
    </section>
  )
}
